### PR TITLE
New pagination system

### PR DESCRIPTION
**Pull request by Digitalone1**
### Requirements 

* [x] Have you ran tests against this code?

### Description of the Change

`simpleSearch` and `getSortedPackages` modified to return the results in array alongside the page and the total pages, so we don't have to make another query on the database. `simpleSearchCount` don't needed anymore.

### CODE REVIEW

**Comment by kyjus25** [comment]
@Digitalone1 `/api/themes` is now returning an array with a single empty object for me, not sure what's up. `/api/themes/search?q=atom` returns as expected.

The `Query-Total` header seems to be returning the total pages instead of the total packages. My intention was to use the "last" pagination Link to return the total pages and the `Query-Total` to return the total number of packages that match the query (regardless of what page/pagination is). Currently they are both returning the same value. 

For instance, using `http://localhost:8080/api/packages/search?q=atom` which contains 3 entries using `start:dev`, if you set the `PAGINATE` value in the .env to 2, I would expect the `last` page to be 2, but the `Query-Total` to be 3. Therefore, page 1 would have 2 results and page 2 would have the remaining 1.

Thanks for your help with this! Excited to get this in!

**Comment by kyjus25** [comment]
## `/api/themes` returning empty object :

Screenshot 2022-12-22 at 4 55 14 PM

## `Query-Total` of 1 even though there are 2 results:

Screenshot 2022-12-22 at 4 55 52 PM

**Comment by Digitalone1** [comment]
Thanks for testing this. 

Query total is the total number of pages. I didn't understand you wanted also the total number of packages, but it can be returned, it's basically the count of the query command.

Never used the chrome dev tool, only tested through the npm, but I should you it too. Will do it tomorrow and push a fix.

**Comment by kyjus25** [comment]
@Digitalone1 Sorry, yes, my hope for the `Query-Total` was to have a way to say "Showing X of XX results" in the pagination bar. The `last` Link is what is able to tell me how many pages are available, so altogether I can create a bar similar to this:

Screenshot 2022-12-22 at 5 36 53 PM

**Comment by Digitalone1** [comment]
@kyjus25 I gave a look and discovered the issue. It was a typo.

Here: https://github.com/kyjus25/package-backend/blob/9769841a83b5a5f95ce88a1b105dc16bac4cb193/src/handlers/theme_handler.js#L82

I had to pass `searchStatus.content.result` like the other parts of the changes.

If you can't do it now, I'll fix it tomorrow.

**Comment by Digitalone1** [comment]
@kyjus25 Regarding the number of packages, you can pick the count of command here:

https://github.com/kyjus25/package-backend/blob/e889acf66487670dfd549c2f363be01a42af3de5/src/database.js#L1348

And add it inside the search status object to return. Something like:

```js
{
  count: resultCount
  page: (page < totalPages) ? page : totalPages,
  total: totalPages,
  result: command.slice((page - 1) * paginated_amount, page * paginated_amount)
}
```

And use it for the query total in the caller.

**Comment by Digitalone1** [comment]
@kyjus25 made an update using the postgreSQL `OVER()` window function as we said on discord.

This should be okay now, but please, make a check you too.

**Comment by Digitalone1** [comment]
Why is this conflicting? It's made merging on the main branch. -_-

**Pull request closed without merging**
